// Loader for content/duas.
// Qur'anic duas are generated by scripts/build-duas.mjs straight from the APIs;
// the prophetic ones are authored and carry needs_verification until checked.
import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';
import { Marked } from 'marked';

const DIR = path.join(process.cwd(), 'content', 'duas');
const md = new Marked({ gfm: true });

export type AyahRef = { surah: number; from: number; to: number };

export type Dua = {
  slug: string;
  title: string;
  kind: 'quranic' | 'prophetic';
  reference: string;
  source: string;
  occasion: string[];
  relatedAyahs: AyahRef[];
  relatedAyahLabels: string[];
  arabic: string;
  transliteration: string | null;
  translation: string;
  noteHtml: string;
  favourite: boolean;
  needsVerification: boolean;
  surah: number | null;
  ayahFrom: number | null;
};

function parseAyahRef(s: string): AyahRef | null {
  const m = String(s).trim().match(/^(\d{1,3}):(\d{1,3})(?:\s*[–—-]\s*(\d{1,3}))?$/);
  if (!m) return null;
  const surah = +m[1];
  if (surah < 1 || surah > 114) return null;
  const from = +m[2];
  return { surah, from, to: Math.max(from, m[3] ? +m[3] : from) };
}

function parse(file: string): Dua {
  const { data, content } = matter(fs.readFileSync(path.join(DIR, file), 'utf8'));
  const labels: string[] = Array.isArray(data.related_ayahs) ? data.related_ayahs.map(String) : [];
  return {
    slug: String(data.slug ?? file.replace(/\.md$/, '')),
    title: String(data.title ?? ''),
    kind: data.kind === 'prophetic' ? 'prophetic' : 'quranic',
    reference: String(data.reference ?? ''),
    source: String(data.source ?? ''),
    occasion: Array.isArray(data.occasion) ? data.occasion.map(String) : [],
    relatedAyahs: labels.map(parseAyahRef).filter((x): x is AyahRef => !!x),
    relatedAyahLabels: labels,
    arabic: String(data.arabic ?? '').trim(),
    transliteration: data.transliteration ? String(data.transliteration).trim() : null,
    translation: String(data.translation ?? '').trim(),
    noteHtml: content.trim() ? (md.parse(content.trim()) as string) : '',
    favourite: data.favourite !== false,
    needsVerification: data.needs_verification === true,
    surah: data.surah == null ? null : Number(data.surah),
    ayahFrom: data.ayah_from == null ? null : Number(data.ayah_from),
  };
}

let cache: Dua[] | null = null;

export function allDuas(): Dua[] {
  if (cache) return cache;
  if (!fs.existsSync(DIR)) return (cache = []);
  cache = fs
    .readdirSync(DIR)
    .filter(f => f.endsWith('.md'))
    .sort()
    .map(parse)
    // Qur'anic duas first, in mushaf order; then the prophetic ones.
    .sort((a, b) => {
      if (a.kind !== b.kind) return a.kind === 'quranic' ? -1 : 1;
      if (a.kind === 'quranic') return (a.surah ?? 0) - (b.surah ?? 0) || (a.ayahFrom ?? 0) - (b.ayahFrom ?? 0);
      return a.title.localeCompare(b.title);
    });
  return cache;
}

export function duasForAyah(surah: number, ayah: number): Dua[] {
  return allDuas().filter(d =>
    d.relatedAyahs.some(r => r.surah === surah && r.from <= ayah && r.to >= ayah)
  );
}

export function duasForSurah(surah: number): Dua[] {
  return allDuas().filter(d => d.relatedAyahs.some(r => r.surah === surah));
}

/** Occasion tags, most used first. */
export function duaOccasions(): { slug: string; count: number }[] {
  const counts = new Map<string, number>();
  for (const d of allDuas()) for (const o of d.occasion) counts.set(o, (counts.get(o) ?? 0) + 1);
  return [...counts.entries()]
    .map(([slug, count]) => ({ slug, count }))
    .sort((a, b) => b.count - a.count || a.slug.localeCompare(b.slug));
}
