// Static surah metadata so pages that only need names and counts
// don't depend on the Quran.com API at build time.
// [transliteration, English meaning, ayah count, revelation place]
type Row = [string, string, number, 'makkah' | 'madinah'];

const ROWS: Row[] = [
  ['Al-Fatihah', 'The Opener', 7, 'makkah'],
  ['Al-Baqarah', 'The Cow', 286, 'madinah'],
  ['Al-Imran', 'Family of Imran', 200, 'madinah'],
  ['An-Nisa', 'The Women', 176, 'madinah'],
  ["Al-Ma'idah", 'The Table Spread', 120, 'madinah'],
  ["Al-An'am", 'The Cattle', 165, 'makkah'],
  ["Al-A'raf", 'The Heights', 206, 'makkah'],
  ['Al-Anfal', 'The Spoils of War', 75, 'madinah'],
  ['At-Tawbah', 'The Repentance', 129, 'madinah'],
  ['Yunus', 'Jonah', 109, 'makkah'],
  ['Hud', 'Hud', 123, 'makkah'],
  ['Yusuf', 'Joseph', 111, 'makkah'],
  ["Ar-Ra'd", 'The Thunder', 43, 'madinah'],
  ['Ibrahim', 'Abraham', 52, 'makkah'],
  ['Al-Hijr', 'The Rocky Tract', 99, 'makkah'],
  ['An-Nahl', 'The Bee', 128, 'makkah'],
  ['Al-Isra', 'The Night Journey', 111, 'makkah'],
  ['Al-Kahf', 'The Cave', 110, 'makkah'],
  ['Maryam', 'Mary', 98, 'makkah'],
  ['Ta Ha', 'Ta-Ha', 135, 'makkah'],
  ['Al-Anbiya', 'The Prophets', 112, 'makkah'],
  ['Al-Hajj', 'The Pilgrimage', 78, 'madinah'],
  ['Al-Muminun', 'The Believers', 118, 'makkah'],
  ['An-Nur', 'The Light', 64, 'madinah'],
  ['Al-Furqan', 'The Criterion', 77, 'makkah'],
  ['Ash-Shuara', 'The Poets', 227, 'makkah'],
  ['An-Naml', 'The Ant', 93, 'makkah'],
  ['Al-Qasas', 'The Stories', 88, 'makkah'],
  ['Al-Ankabut', 'The Spider', 69, 'makkah'],
  ['Ar-Rum', 'The Romans', 60, 'makkah'],
  ['Luqman', 'Luqman', 34, 'makkah'],
  ['As-Sajdah', 'The Prostration', 30, 'makkah'],
  ['Al-Ahzab', 'The Combined Forces', 73, 'madinah'],
  ['Saba', 'Sheba', 54, 'makkah'],
  ['Fatir', 'The Originator', 45, 'makkah'],
  ['Ya Sin', 'Ya Sin', 83, 'makkah'],
  ['As-Saffat', 'Those Who Set the Ranks', 182, 'makkah'],
  ['Saad', 'The Letter Saad', 88, 'makkah'],
  ['Az-Zumar', 'The Troops', 75, 'makkah'],
  ['Ghafir', 'The Forgiver', 85, 'makkah'],
  ['Fussilat', 'Explained in Detail', 54, 'makkah'],
  ['Ash-Shura', 'The Consultation', 53, 'makkah'],
  ['Az-Zukhruf', 'The Ornaments of Gold', 89, 'makkah'],
  ['Ad-Dukhan', 'The Smoke', 59, 'makkah'],
  ['Al-Jathiyah', 'The Crouching', 37, 'makkah'],
  ['Al-Ahqaf', 'The Wind-Curved Sandhills', 35, 'makkah'],
  ['Muhammad', 'Muhammad', 38, 'madinah'],
  ['Al-Fath', 'The Victory', 29, 'madinah'],
  ['Al-Hujurat', 'The Rooms', 18, 'madinah'],
  ['Qaf', 'The Letter Qaf', 45, 'makkah'],
  ['Adh-Dhariyat', 'The Winnowing Winds', 60, 'makkah'],
  ['At-Tur', 'The Mount', 49, 'makkah'],
  ['An-Najm', 'The Star', 62, 'makkah'],
  ['Al-Qamar', 'The Moon', 55, 'makkah'],
  ['Ar-Rahman', 'The Most Merciful', 78, 'madinah'],
  ["Al-Waqi'ah", 'The Inevitable', 96, 'makkah'],
  ['Al-Hadid', 'The Iron', 29, 'madinah'],
  ['Al-Mujadilah', 'The Pleading Woman', 22, 'madinah'],
  ['Al-Hashr', 'The Exile', 24, 'madinah'],
  ['Al-Mumtahinah', 'She Who Is Examined', 13, 'madinah'],
  ['As-Saff', 'The Ranks', 14, 'madinah'],
  ['Al-Jumuah', 'Friday', 11, 'madinah'],
  ['Al-Munafiqun', 'The Hypocrites', 11, 'madinah'],
  ['At-Taghabun', 'The Mutual Loss and Gain', 18, 'madinah'],
  ['At-Talaq', 'The Divorce', 12, 'madinah'],
  ['At-Tahrim', 'The Prohibition', 12, 'madinah'],
  ['Al-Mulk', 'The Dominion', 30, 'makkah'],
  ['Al-Qalam', 'The Pen', 52, 'makkah'],
  ['Al-Haqqah', 'The Reality', 52, 'makkah'],
  ["Al-Ma'arij", 'The Ascending Stairways', 44, 'makkah'],
  ['Nuh', 'Noah', 28, 'makkah'],
  ['Al-Jinn', 'The Jinn', 28, 'makkah'],
  ['Al-Muzzammil', 'The Enshrouded One', 20, 'makkah'],
  ['Al-Muddaththir', 'The Cloaked One', 56, 'makkah'],
  ['Al-Qiyamah', 'The Resurrection', 40, 'makkah'],
  ['Al-Insan', 'Man', 31, 'madinah'],
  ['Al-Mursalat', 'Those Sent Forth', 50, 'makkah'],
  ['An-Naba', 'The Tidings', 40, 'makkah'],
  ["An-Nazi'at", 'Those Who Pull Out', 46, 'makkah'],
  ['Abasa', 'He Frowned', 42, 'makkah'],
  ['At-Takwir', 'The Folding Up', 29, 'makkah'],
  ['Al-Infitar', 'The Cleaving', 19, 'makkah'],
  ['Al-Mutaffifin', 'Those Who Give Short Measure', 36, 'makkah'],
  ['Al-Inshiqaq', 'The Splitting Open', 25, 'makkah'],
  ['Al-Buruj', 'The Great Constellations', 22, 'makkah'],
  ['At-Tariq', 'The Night Star', 17, 'makkah'],
  ["Al-A'la", 'The Most High', 19, 'makkah'],
  ['Al-Ghashiyah', 'The Overwhelming', 26, 'makkah'],
  ['Al-Fajr', 'The Dawn', 30, 'makkah'],
  ['Al-Balad', 'The City', 20, 'makkah'],
  ['Ash-Shams', 'The Sun', 15, 'makkah'],
  ['Al-Layl', 'The Night', 21, 'makkah'],
  ['Ad-Duha', 'The Morning Brightness', 11, 'makkah'],
  ['Ash-Sharh', 'The Relief', 8, 'makkah'],
  ['At-Tin', 'The Fig', 8, 'makkah'],
  ["Al-'Alaq", 'The Clinging Clot', 19, 'makkah'],
  ['Al-Qadr', 'The Night of Decree', 5, 'makkah'],
  ['Al-Bayyinah', 'The Clear Proof', 8, 'madinah'],
  ['Az-Zalzalah', 'The Earthquake', 8, 'madinah'],
  ["Al-'Adiyat", 'The Chargers', 11, 'makkah'],
  ["Al-Qari'ah", 'The Striking Calamity', 11, 'makkah'],
  ['At-Takathur', 'The Rivalry in Increase', 8, 'makkah'],
  ["Al-'Asr", 'Time', 3, 'makkah'],
  ['Al-Humazah', 'The Slanderer', 9, 'makkah'],
  ['Al-Fil', 'The Elephant', 5, 'makkah'],
  ['Quraysh', 'Quraysh', 4, 'makkah'],
  ["Al-Ma'un", 'Small Kindnesses', 7, 'makkah'],
  ['Al-Kawthar', 'Abundance', 3, 'makkah'],
  ['Al-Kafirun', 'The Disbelievers', 6, 'makkah'],
  ['An-Nasr', 'The Help', 3, 'madinah'],
  ['Al-Masad', 'The Palm Fibre', 5, 'makkah'],
  ['Al-Ikhlas', 'Sincerity', 4, 'makkah'],
  ['Al-Falaq', 'The Daybreak', 5, 'makkah'],
  ['An-Nas', 'Mankind', 6, 'makkah'],
];

export type SurahMeta = { n: number; name: string; meaning: string; ayat: number; place: 'makkah' | 'madinah' };

export const SURAHS: SurahMeta[] = ROWS.map(([name, meaning, ayat, place], i) => ({ n: i + 1, name, meaning, ayat, place }));

export function surahMeta(n: number): SurahMeta | undefined {
  return SURAHS[n - 1];
}
